org: fernando
app: hello-cicd
service: python-hello-cicd-api

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs8.10

functions:
  currentTime:
    handler: handler.handler
    events:
      - http:
          path: ping
          method: get