org: fernando
app: hello-cicd
service: hello-cicd-api

frameworkVersion: ">=1.5.0 <2.0.0"

provider:
  name: aws
  runtime: python3.7

functions:
  currentTime:
    handler: handler.endpoint
    events:
      - http:
          path: ping
          method: get